name: CI on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Mostrar autor del commit
        run: echo "Este cambio fue hecho por ${{ github.actor }}"
